name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  spec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version:
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
        gemfile:
          - "rails70"
          - "rails71"
          - "rails72"
          - "rails80"
        exclude:
          - ruby_version: "3.1"
            gemfile: "rails80"
        include:
          - ruby_version: "head"
            gemfile: "rails-main"

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true

    - name: Run Tests
      run: bundle exec rake
